DROP TABLE IF EXISTS device;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS device_credentials;
DROP TABLE IF EXISTS relation;
DROP TABLE IF EXISTS tenant;
DROP TABLE IF EXISTS ts_kv;
DROP TABLE IF EXISTS ts_kv_latest;
DROP TABLE IF EXISTS entity_view;
